<?php
/**
 * OutboundDeliveryDocumentFlowsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Outbound Delivery (A2X)
 *
 * This service enables you to create, read, update and delete outbound deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\OutboundDelivery\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use BeLenka\SAP\OutboundDelivery\ApiException;
use BeLenka\SAP\OutboundDelivery\Configuration;
use BeLenka\SAP\OutboundDelivery\HeaderSelector;
use BeLenka\SAP\OutboundDelivery\ObjectSerializer;

/**
 * OutboundDeliveryDocumentFlowsApi Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OutboundDeliveryDocumentFlowsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet' => [
            'application/json',
        ],
        'aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch' => [
            'application/json',
        ],
        'aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet
     *
     * Reads outbound delivery document flows by key.
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryDocFlowType|\BeLenka\SAP\OutboundDelivery\Model\Error
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet($preceding_document, $preceding_document_item, $subsequent_document_category, $select = null, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'][0])
    {
        list($response) = $this->aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetWithHttpInfo($preceding_document, $preceding_document_item, $subsequent_document_category, $select, $contentType);
        return $response;
    }

    /**
     * Operation aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetWithHttpInfo
     *
     * Reads outbound delivery document flows by key.
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryDocFlowType|\BeLenka\SAP\OutboundDelivery\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetWithHttpInfo($preceding_document, $preceding_document_item, $subsequent_document_category, $select = null, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'][0])
    {
        $request = $this->aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetRequest($preceding_document, $preceding_document_item, $subsequent_document_category, $select, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryDocFlowType' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryDocFlowType' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryDocFlowType', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryDocFlowType';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryDocFlowType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetAsync
     *
     * Reads outbound delivery document flows by key.
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetAsync($preceding_document, $preceding_document_item, $subsequent_document_category, $select = null, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'][0])
    {
        return $this->aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetAsyncWithHttpInfo($preceding_document, $preceding_document_item, $subsequent_document_category, $select, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetAsyncWithHttpInfo
     *
     * Reads outbound delivery document flows by key.
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetAsyncWithHttpInfo($preceding_document, $preceding_document_item, $subsequent_document_category, $select = null, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'][0])
    {
        $returnType = '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryDocFlowType';
        $request = $this->aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetRequest($preceding_document, $preceding_document_item, $subsequent_document_category, $select, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGetRequest($preceding_document, $preceding_document_item, $subsequent_document_category, $select = null, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'][0])
    {

        // verify the required parameter 'preceding_document' is set
        if ($preceding_document === null || (is_array($preceding_document) && count($preceding_document) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $preceding_document when calling aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'
            );
        }
        if (strlen($preceding_document) > 10) {
            throw new \InvalidArgumentException('invalid length for "$preceding_document" when calling OutboundDeliveryDocumentFlowsApi.aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'preceding_document_item' is set
        if ($preceding_document_item === null || (is_array($preceding_document_item) && count($preceding_document_item) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $preceding_document_item when calling aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'
            );
        }
        if (strlen($preceding_document_item) > 6) {
            throw new \InvalidArgumentException('invalid length for "$preceding_document_item" when calling OutboundDeliveryDocumentFlowsApi.aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet, must be smaller than or equal to 6.');
        }
        
        // verify the required parameter 'subsequent_document_category' is set
        if ($subsequent_document_category === null || (is_array($subsequent_document_category) && count($subsequent_document_category) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $subsequent_document_category when calling aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet'
            );
        }
        if (strlen($subsequent_document_category) > 4) {
            throw new \InvalidArgumentException('invalid length for "$subsequent_document_category" when calling OutboundDeliveryDocumentFlowsApi.aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryGet, must be smaller than or equal to 4.');
        }
        
        

        $resourcePath = '/A_OutbDeliveryDocFlow(PrecedingDocument=\'{PrecedingDocument}\',PrecedingDocumentItem=\'{PrecedingDocumentItem}\',SubsequentDocumentCategory=\'{SubsequentDocumentCategory}\')';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($preceding_document !== null) {
            $resourcePath = str_replace(
                '{' . 'PrecedingDocument' . '}',
                ObjectSerializer::toPathValue($preceding_document),
                $resourcePath
            );
        }
        // path params
        if ($preceding_document_item !== null) {
            $resourcePath = str_replace(
                '{' . 'PrecedingDocumentItem' . '}',
                ObjectSerializer::toPathValue($preceding_document_item),
                $resourcePath
            );
        }
        // path params
        if ($subsequent_document_category !== null) {
            $resourcePath = str_replace(
                '{' . 'SubsequentDocumentCategory' . '}',
                ObjectSerializer::toPathValue($subsequent_document_category),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch
     *
     * Updates outbound delivery document flows.
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  \BeLenka\SAP\OutboundDelivery\Model\ModifiedAOutbDeliveryDocFlowType $modified_a_outb_delivery_doc_flow_type New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch($preceding_document, $preceding_document_item, $subsequent_document_category, $modified_a_outb_delivery_doc_flow_type, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'][0])
    {
        $this->aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchWithHttpInfo($preceding_document, $preceding_document_item, $subsequent_document_category, $modified_a_outb_delivery_doc_flow_type, $contentType);
    }

    /**
     * Operation aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchWithHttpInfo
     *
     * Updates outbound delivery document flows.
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  \BeLenka\SAP\OutboundDelivery\Model\ModifiedAOutbDeliveryDocFlowType $modified_a_outb_delivery_doc_flow_type New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchWithHttpInfo($preceding_document, $preceding_document_item, $subsequent_document_category, $modified_a_outb_delivery_doc_flow_type, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'][0])
    {
        $request = $this->aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchRequest($preceding_document, $preceding_document_item, $subsequent_document_category, $modified_a_outb_delivery_doc_flow_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                
            }
            throw $e;
        }
    }

    /**
     * Operation aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchAsync
     *
     * Updates outbound delivery document flows.
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  \BeLenka\SAP\OutboundDelivery\Model\ModifiedAOutbDeliveryDocFlowType $modified_a_outb_delivery_doc_flow_type New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchAsync($preceding_document, $preceding_document_item, $subsequent_document_category, $modified_a_outb_delivery_doc_flow_type, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'][0])
    {
        return $this->aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchAsyncWithHttpInfo($preceding_document, $preceding_document_item, $subsequent_document_category, $modified_a_outb_delivery_doc_flow_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchAsyncWithHttpInfo
     *
     * Updates outbound delivery document flows.
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  \BeLenka\SAP\OutboundDelivery\Model\ModifiedAOutbDeliveryDocFlowType $modified_a_outb_delivery_doc_flow_type New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchAsyncWithHttpInfo($preceding_document, $preceding_document_item, $subsequent_document_category, $modified_a_outb_delivery_doc_flow_type, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'][0])
    {
        $returnType = '';
        $request = $this->aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchRequest($preceding_document, $preceding_document_item, $subsequent_document_category, $modified_a_outb_delivery_doc_flow_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'
     *
     * @param  string $preceding_document Preceding Doc. (required)
     * @param  string $preceding_document_item Preceding Item (required)
     * @param  string $subsequent_document_category Subs.Doc.Categ. (required)
     * @param  \BeLenka\SAP\OutboundDelivery\Model\ModifiedAOutbDeliveryDocFlowType $modified_a_outb_delivery_doc_flow_type New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatchRequest($preceding_document, $preceding_document_item, $subsequent_document_category, $modified_a_outb_delivery_doc_flow_type, string $contentType = self::contentTypes['aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'][0])
    {

        // verify the required parameter 'preceding_document' is set
        if ($preceding_document === null || (is_array($preceding_document) && count($preceding_document) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $preceding_document when calling aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'
            );
        }
        if (strlen($preceding_document) > 10) {
            throw new \InvalidArgumentException('invalid length for "$preceding_document" when calling OutboundDeliveryDocumentFlowsApi.aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'preceding_document_item' is set
        if ($preceding_document_item === null || (is_array($preceding_document_item) && count($preceding_document_item) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $preceding_document_item when calling aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'
            );
        }
        if (strlen($preceding_document_item) > 6) {
            throw new \InvalidArgumentException('invalid length for "$preceding_document_item" when calling OutboundDeliveryDocumentFlowsApi.aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch, must be smaller than or equal to 6.');
        }
        
        // verify the required parameter 'subsequent_document_category' is set
        if ($subsequent_document_category === null || (is_array($subsequent_document_category) && count($subsequent_document_category) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $subsequent_document_category when calling aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'
            );
        }
        if (strlen($subsequent_document_category) > 4) {
            throw new \InvalidArgumentException('invalid length for "$subsequent_document_category" when calling OutboundDeliveryDocumentFlowsApi.aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch, must be smaller than or equal to 4.');
        }
        
        // verify the required parameter 'modified_a_outb_delivery_doc_flow_type' is set
        if ($modified_a_outb_delivery_doc_flow_type === null || (is_array($modified_a_outb_delivery_doc_flow_type) && count($modified_a_outb_delivery_doc_flow_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $modified_a_outb_delivery_doc_flow_type when calling aOutbDeliveryDocFlowPrecedingDocumentPrecedingDocumentPrecedingDocumentItemPrecedingDocumentItemSubsequentDocumentCategorySubsequentDocumentCategoryPatch'
            );
        }


        $resourcePath = '/A_OutbDeliveryDocFlow(PrecedingDocument=\'{PrecedingDocument}\',PrecedingDocumentItem=\'{PrecedingDocumentItem}\',SubsequentDocumentCategory=\'{SubsequentDocumentCategory}\')';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($preceding_document !== null) {
            $resourcePath = str_replace(
                '{' . 'PrecedingDocument' . '}',
                ObjectSerializer::toPathValue($preceding_document),
                $resourcePath
            );
        }
        // path params
        if ($preceding_document_item !== null) {
            $resourcePath = str_replace(
                '{' . 'PrecedingDocumentItem' . '}',
                ObjectSerializer::toPathValue($preceding_document_item),
                $resourcePath
            );
        }
        // path params
        if ($subsequent_document_category !== null) {
            $resourcePath = str_replace(
                '{' . 'SubsequentDocumentCategory' . '}',
                ObjectSerializer::toPathValue($subsequent_document_category),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($modified_a_outb_delivery_doc_flow_type)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($modified_a_outb_delivery_doc_flow_type));
            } else {
                $httpBody = $modified_a_outb_delivery_doc_flow_type;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet
     *
     * Reads document flows of specific outbound delivery item.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\OutboundDelivery\Model\Wrapper2|\BeLenka\SAP\OutboundDelivery\Model\Error
     */
    public function aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet($delivery_document, $delivery_document_item, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'][0])
    {
        list($response) = $this->aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetWithHttpInfo($delivery_document, $delivery_document_item, $filter, $inlinecount, $select, $contentType);
        return $response;
    }

    /**
     * Operation aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetWithHttpInfo
     *
     * Reads document flows of specific outbound delivery item.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\OutboundDelivery\Model\Wrapper2|\BeLenka\SAP\OutboundDelivery\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetWithHttpInfo($delivery_document, $delivery_document_item, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'][0])
    {
        $request = $this->aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetRequest($delivery_document, $delivery_document_item, $filter, $inlinecount, $select, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\OutboundDelivery\Model\Wrapper2' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\OutboundDelivery\Model\Wrapper2' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\OutboundDelivery\Model\Wrapper2', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\OutboundDelivery\Model\Wrapper2';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\OutboundDelivery\Model\Wrapper2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetAsync
     *
     * Reads document flows of specific outbound delivery item.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetAsync($delivery_document, $delivery_document_item, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'][0])
    {
        return $this->aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetAsyncWithHttpInfo($delivery_document, $delivery_document_item, $filter, $inlinecount, $select, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetAsyncWithHttpInfo
     *
     * Reads document flows of specific outbound delivery item.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetAsyncWithHttpInfo($delivery_document, $delivery_document_item, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'][0])
    {
        $returnType = '\BeLenka\SAP\OutboundDelivery\Model\Wrapper2';
        $request = $this->aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetRequest($delivery_document, $delivery_document_item, $filter, $inlinecount, $select, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGetRequest($delivery_document, $delivery_document_item, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'][0])
    {

        // verify the required parameter 'delivery_document' is set
        if ($delivery_document === null || (is_array($delivery_document) && count($delivery_document) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $delivery_document when calling aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'
            );
        }
        if (strlen($delivery_document) > 10) {
            throw new \InvalidArgumentException('invalid length for "$delivery_document" when calling OutboundDeliveryDocumentFlowsApi.aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'delivery_document_item' is set
        if ($delivery_document_item === null || (is_array($delivery_document_item) && count($delivery_document_item) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $delivery_document_item when calling aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet'
            );
        }
        if (strlen($delivery_document_item) > 6) {
            throw new \InvalidArgumentException('invalid length for "$delivery_document_item" when calling OutboundDeliveryDocumentFlowsApi.aOutbDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToDocumentFlowGet, must be smaller than or equal to 6.');
        }
        


        

        $resourcePath = '/A_OutbDeliveryItem(DeliveryDocument=\'{DeliveryDocument}\',DeliveryDocumentItem=\'{DeliveryDocumentItem}\')/to_DocumentFlow';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            '$filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $inlinecount,
            '$inlinecount', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($delivery_document !== null) {
            $resourcePath = str_replace(
                '{' . 'DeliveryDocument' . '}',
                ObjectSerializer::toPathValue($delivery_document),
                $resourcePath
            );
        }
        // path params
        if ($delivery_document_item !== null) {
            $resourcePath = str_replace(
                '{' . 'DeliveryDocumentItem' . '}',
                ObjectSerializer::toPathValue($delivery_document_item),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
