<?php
/**
 * OutboundDeliveryPartnersApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Outbound Delivery (A2X)
 *
 * This service enables you to create, read, update and delete outbound deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\OutboundDelivery\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use BeLenka\SAP\OutboundDelivery\ApiException;
use BeLenka\SAP\OutboundDelivery\Configuration;
use BeLenka\SAP\OutboundDelivery\HeaderSelector;
use BeLenka\SAP\OutboundDelivery\ObjectSerializer;

/**
 * OutboundDeliveryPartnersApi Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OutboundDeliveryPartnersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet' => [
            'application/json',
        ],
        'aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get' => [
            'application/json',
        ],
        'aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet
     *
     * Reads partners of specific outbound delivery header.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\OutboundDelivery\Model\Wrapper7|\BeLenka\SAP\OutboundDelivery\Model\Error
     */
    public function aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet($delivery_document, $filter = null, $inlinecount = null, $select = null, $expand = null, string $contentType = self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'][0])
    {
        list($response) = $this->aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetWithHttpInfo($delivery_document, $filter, $inlinecount, $select, $expand, $contentType);
        return $response;
    }

    /**
     * Operation aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetWithHttpInfo
     *
     * Reads partners of specific outbound delivery header.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\OutboundDelivery\Model\Wrapper7|\BeLenka\SAP\OutboundDelivery\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetWithHttpInfo($delivery_document, $filter = null, $inlinecount = null, $select = null, $expand = null, string $contentType = self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'][0])
    {
        $request = $this->aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetRequest($delivery_document, $filter, $inlinecount, $select, $expand, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\OutboundDelivery\Model\Wrapper7' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\OutboundDelivery\Model\Wrapper7' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\OutboundDelivery\Model\Wrapper7', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\OutboundDelivery\Model\Wrapper7';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\OutboundDelivery\Model\Wrapper7',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetAsync
     *
     * Reads partners of specific outbound delivery header.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetAsync($delivery_document, $filter = null, $inlinecount = null, $select = null, $expand = null, string $contentType = self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'][0])
    {
        return $this->aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetAsyncWithHttpInfo($delivery_document, $filter, $inlinecount, $select, $expand, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetAsyncWithHttpInfo
     *
     * Reads partners of specific outbound delivery header.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetAsyncWithHttpInfo($delivery_document, $filter = null, $inlinecount = null, $select = null, $expand = null, string $contentType = self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'][0])
    {
        $returnType = '\BeLenka\SAP\OutboundDelivery\Model\Wrapper7';
        $request = $this->aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetRequest($delivery_document, $filter, $inlinecount, $select, $expand, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGetRequest($delivery_document, $filter = null, $inlinecount = null, $select = null, $expand = null, string $contentType = self::contentTypes['aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'][0])
    {

        // verify the required parameter 'delivery_document' is set
        if ($delivery_document === null || (is_array($delivery_document) && count($delivery_document) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $delivery_document when calling aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet'
            );
        }
        if (strlen($delivery_document) > 10) {
            throw new \InvalidArgumentException('invalid length for "$delivery_document" when calling OutboundDeliveryPartnersApi.aOutbDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet, must be smaller than or equal to 10.');
        }
        


        
        

        $resourcePath = '/A_OutbDeliveryHeader(\'{DeliveryDocument}\')/to_DeliveryDocumentPartner';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            '$filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $inlinecount,
            '$inlinecount', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expand,
            '$expand', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($delivery_document !== null) {
            $resourcePath = str_replace(
                '{' . 'DeliveryDocument' . '}',
                ObjectSerializer::toPathValue($delivery_document),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get
     *
     * Reads addresses of specific outbound delivery partner.
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddress2Type|\BeLenka\SAP\OutboundDelivery\Model\Error
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'][0])
    {
        list($response) = $this->aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetWithHttpInfo($partner_function, $sd_document, $select, $contentType);
        return $response;
    }

    /**
     * Operation aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetWithHttpInfo
     *
     * Reads addresses of specific outbound delivery partner.
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddress2Type|\BeLenka\SAP\OutboundDelivery\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetWithHttpInfo($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'][0])
    {
        $request = $this->aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetRequest($partner_function, $sd_document, $select, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddress2Type' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddress2Type' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddress2Type', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddress2Type';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddress2Type',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetAsync
     *
     * Reads addresses of specific outbound delivery partner.
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetAsync($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'][0])
    {
        return $this->aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetAsyncWithHttpInfo($partner_function, $sd_document, $select, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetAsyncWithHttpInfo
     *
     * Reads addresses of specific outbound delivery partner.
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetAsyncWithHttpInfo($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'][0])
    {
        $returnType = '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddress2Type';
        $request = $this->aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetRequest($partner_function, $sd_document, $select, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2GetRequest($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'][0])
    {

        // verify the required parameter 'partner_function' is set
        if ($partner_function === null || (is_array($partner_function) && count($partner_function) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $partner_function when calling aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'
            );
        }
        if (strlen($partner_function) > 2) {
            throw new \InvalidArgumentException('invalid length for "$partner_function" when calling OutboundDeliveryPartnersApi.aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get, must be smaller than or equal to 2.');
        }
        
        // verify the required parameter 'sd_document' is set
        if ($sd_document === null || (is_array($sd_document) && count($sd_document) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sd_document when calling aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get'
            );
        }
        if (strlen($sd_document) > 10) {
            throw new \InvalidArgumentException('invalid length for "$sd_document" when calling OutboundDeliveryPartnersApi.aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddress2Get, must be smaller than or equal to 10.');
        }
        
        

        $resourcePath = '/A_OutbDeliveryPartner(PartnerFunction=\'{PartnerFunction}\',SDDocument=\'{SDDocument}\')/to_Address2';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($partner_function !== null) {
            $resourcePath = str_replace(
                '{' . 'PartnerFunction' . '}',
                ObjectSerializer::toPathValue($partner_function),
                $resourcePath
            );
        }
        // path params
        if ($sd_document !== null) {
            $resourcePath = str_replace(
                '{' . 'SDDocument' . '}',
                ObjectSerializer::toPathValue($sd_document),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet
     *
     * Reads addresses of specific outbound delivery partner.
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddressType|\BeLenka\SAP\OutboundDelivery\Model\Error
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'][0])
    {
        list($response) = $this->aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetWithHttpInfo($partner_function, $sd_document, $select, $contentType);
        return $response;
    }

    /**
     * Operation aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetWithHttpInfo
     *
     * Reads addresses of specific outbound delivery partner.
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\OutboundDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddressType|\BeLenka\SAP\OutboundDelivery\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetWithHttpInfo($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'][0])
    {
        $request = $this->aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetRequest($partner_function, $sd_document, $select, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddressType' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddressType' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddressType', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddressType';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddressType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetAsync
     *
     * Reads addresses of specific outbound delivery partner.
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetAsync($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'][0])
    {
        return $this->aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetAsyncWithHttpInfo($partner_function, $sd_document, $select, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetAsyncWithHttpInfo
     *
     * Reads addresses of specific outbound delivery partner.
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetAsyncWithHttpInfo($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'][0])
    {
        $returnType = '\BeLenka\SAP\OutboundDelivery\Model\AOutbDeliveryAddressType';
        $request = $this->aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetRequest($partner_function, $sd_document, $select, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'
     *
     * @param  string $partner_function Partner Functn (required)
     * @param  string $sd_document SD Document (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGetRequest($partner_function, $sd_document, $select = null, string $contentType = self::contentTypes['aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'][0])
    {

        // verify the required parameter 'partner_function' is set
        if ($partner_function === null || (is_array($partner_function) && count($partner_function) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $partner_function when calling aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'
            );
        }
        if (strlen($partner_function) > 2) {
            throw new \InvalidArgumentException('invalid length for "$partner_function" when calling OutboundDeliveryPartnersApi.aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet, must be smaller than or equal to 2.');
        }
        
        // verify the required parameter 'sd_document' is set
        if ($sd_document === null || (is_array($sd_document) && count($sd_document) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sd_document when calling aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet'
            );
        }
        if (strlen($sd_document) > 10) {
            throw new \InvalidArgumentException('invalid length for "$sd_document" when calling OutboundDeliveryPartnersApi.aOutbDeliveryPartnerPartnerFunctionPartnerFunctionSDDocumentSDDocumentToAddressGet, must be smaller than or equal to 10.');
        }
        
        

        $resourcePath = '/A_OutbDeliveryPartner(PartnerFunction=\'{PartnerFunction}\',SDDocument=\'{SDDocument}\')/to_Address';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($partner_function !== null) {
            $resourcePath = str_replace(
                '{' . 'PartnerFunction' . '}',
                ObjectSerializer::toPathValue($partner_function),
                $resourcePath
            );
        }
        // path params
        if ($sd_document !== null) {
            $resourcePath = str_replace(
                '{' . 'SDDocument' . '}',
                ObjectSerializer::toPathValue($sd_document),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
