<?php
/**
 * APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Outbound Delivery (A2X)
 *
 * This service enables you to create, read, update and delete outbound deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\OutboundDelivery\Model;

use \ArrayAccess;
use \BeLenka\SAP\OutboundDelivery\ObjectSerializer;

/**
 * APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'API_OUTBOUND_DELIVERY_SRV.A_HandlingUnitItemDeliveryType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'batch' => 'string',
        'delivery_document' => 'string',
        'delivery_document_item' => 'string',
        'handling_unit_external_id' => 'string',
        'handling_unit_internal_id' => 'string',
        'handling_unit_item' => 'string',
        'handling_unit_nested_internal_id' => 'string',
        'handling_unit_nr_of_aux_packg_mat' => 'int',
        'handling_unit_number_of_serialnumb' => 'int',
        'handling_unit_quantity' => 'float',
        'handling_unit_quantity_unit' => 'string',
        'handling_unit_type_of_content' => 'string',
        'material' => 'string',
        'material_by_customer' => 'string',
        'material_name' => 'string',
        'serial_number_profile' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'batch' => null,
        'delivery_document' => null,
        'delivery_document_item' => null,
        'handling_unit_external_id' => null,
        'handling_unit_internal_id' => null,
        'handling_unit_item' => null,
        'handling_unit_nested_internal_id' => null,
        'handling_unit_nr_of_aux_packg_mat' => 'int32',
        'handling_unit_number_of_serialnumb' => 'int32',
        'handling_unit_quantity' => 'decimal',
        'handling_unit_quantity_unit' => null,
        'handling_unit_type_of_content' => null,
        'material' => null,
        'material_by_customer' => null,
        'material_name' => null,
        'serial_number_profile' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'batch' => false,
		'delivery_document' => false,
		'delivery_document_item' => false,
		'handling_unit_external_id' => false,
		'handling_unit_internal_id' => false,
		'handling_unit_item' => false,
		'handling_unit_nested_internal_id' => false,
		'handling_unit_nr_of_aux_packg_mat' => false,
		'handling_unit_number_of_serialnumb' => false,
		'handling_unit_quantity' => false,
		'handling_unit_quantity_unit' => false,
		'handling_unit_type_of_content' => false,
		'material' => false,
		'material_by_customer' => false,
		'material_name' => false,
		'serial_number_profile' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'batch' => 'Batch',
        'delivery_document' => 'DeliveryDocument',
        'delivery_document_item' => 'DeliveryDocumentItem',
        'handling_unit_external_id' => 'HandlingUnitExternalId',
        'handling_unit_internal_id' => 'HandlingUnitInternalId',
        'handling_unit_item' => 'HandlingUnitItem',
        'handling_unit_nested_internal_id' => 'HandlingUnitNestedInternalId',
        'handling_unit_nr_of_aux_packg_mat' => 'HandlingUnitNrOfAuxPackgMat',
        'handling_unit_number_of_serialnumb' => 'HandlingUnitNumberOfSerialnumb',
        'handling_unit_quantity' => 'HandlingUnitQuantity',
        'handling_unit_quantity_unit' => 'HandlingUnitQuantityUnit',
        'handling_unit_type_of_content' => 'HandlingUnitTypeOfContent',
        'material' => 'Material',
        'material_by_customer' => 'MaterialByCustomer',
        'material_name' => 'MaterialName',
        'serial_number_profile' => 'SerialNumberProfile'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'batch' => 'setBatch',
        'delivery_document' => 'setDeliveryDocument',
        'delivery_document_item' => 'setDeliveryDocumentItem',
        'handling_unit_external_id' => 'setHandlingUnitExternalId',
        'handling_unit_internal_id' => 'setHandlingUnitInternalId',
        'handling_unit_item' => 'setHandlingUnitItem',
        'handling_unit_nested_internal_id' => 'setHandlingUnitNestedInternalId',
        'handling_unit_nr_of_aux_packg_mat' => 'setHandlingUnitNrOfAuxPackgMat',
        'handling_unit_number_of_serialnumb' => 'setHandlingUnitNumberOfSerialnumb',
        'handling_unit_quantity' => 'setHandlingUnitQuantity',
        'handling_unit_quantity_unit' => 'setHandlingUnitQuantityUnit',
        'handling_unit_type_of_content' => 'setHandlingUnitTypeOfContent',
        'material' => 'setMaterial',
        'material_by_customer' => 'setMaterialByCustomer',
        'material_name' => 'setMaterialName',
        'serial_number_profile' => 'setSerialNumberProfile'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'batch' => 'getBatch',
        'delivery_document' => 'getDeliveryDocument',
        'delivery_document_item' => 'getDeliveryDocumentItem',
        'handling_unit_external_id' => 'getHandlingUnitExternalId',
        'handling_unit_internal_id' => 'getHandlingUnitInternalId',
        'handling_unit_item' => 'getHandlingUnitItem',
        'handling_unit_nested_internal_id' => 'getHandlingUnitNestedInternalId',
        'handling_unit_nr_of_aux_packg_mat' => 'getHandlingUnitNrOfAuxPackgMat',
        'handling_unit_number_of_serialnumb' => 'getHandlingUnitNumberOfSerialnumb',
        'handling_unit_quantity' => 'getHandlingUnitQuantity',
        'handling_unit_quantity_unit' => 'getHandlingUnitQuantityUnit',
        'handling_unit_type_of_content' => 'getHandlingUnitTypeOfContent',
        'material' => 'getMaterial',
        'material_by_customer' => 'getMaterialByCustomer',
        'material_name' => 'getMaterialName',
        'serial_number_profile' => 'getSerialNumberProfile'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('batch', $data ?? [], null);
        $this->setIfExists('delivery_document', $data ?? [], null);
        $this->setIfExists('delivery_document_item', $data ?? [], null);
        $this->setIfExists('handling_unit_external_id', $data ?? [], null);
        $this->setIfExists('handling_unit_internal_id', $data ?? [], null);
        $this->setIfExists('handling_unit_item', $data ?? [], null);
        $this->setIfExists('handling_unit_nested_internal_id', $data ?? [], null);
        $this->setIfExists('handling_unit_nr_of_aux_packg_mat', $data ?? [], null);
        $this->setIfExists('handling_unit_number_of_serialnumb', $data ?? [], null);
        $this->setIfExists('handling_unit_quantity', $data ?? [], null);
        $this->setIfExists('handling_unit_quantity_unit', $data ?? [], null);
        $this->setIfExists('handling_unit_type_of_content', $data ?? [], null);
        $this->setIfExists('material', $data ?? [], null);
        $this->setIfExists('material_by_customer', $data ?? [], null);
        $this->setIfExists('material_name', $data ?? [], null);
        $this->setIfExists('serial_number_profile', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['batch']) && (mb_strlen($this->container['batch']) > 10)) {
            $invalidProperties[] = "invalid value for 'batch', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['delivery_document']) && (mb_strlen($this->container['delivery_document']) > 10)) {
            $invalidProperties[] = "invalid value for 'delivery_document', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['delivery_document_item']) && (mb_strlen($this->container['delivery_document_item']) > 6)) {
            $invalidProperties[] = "invalid value for 'delivery_document_item', the character length must be smaller than or equal to 6.";
        }

        if (!is_null($this->container['handling_unit_external_id']) && (mb_strlen($this->container['handling_unit_external_id']) > 20)) {
            $invalidProperties[] = "invalid value for 'handling_unit_external_id', the character length must be smaller than or equal to 20.";
        }

        if (!is_null($this->container['handling_unit_internal_id']) && (mb_strlen($this->container['handling_unit_internal_id']) > 10)) {
            $invalidProperties[] = "invalid value for 'handling_unit_internal_id', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['handling_unit_item']) && (mb_strlen($this->container['handling_unit_item']) > 6)) {
            $invalidProperties[] = "invalid value for 'handling_unit_item', the character length must be smaller than or equal to 6.";
        }

        if (!is_null($this->container['handling_unit_nested_internal_id']) && (mb_strlen($this->container['handling_unit_nested_internal_id']) > 10)) {
            $invalidProperties[] = "invalid value for 'handling_unit_nested_internal_id', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['handling_unit_quantity_unit']) && (mb_strlen($this->container['handling_unit_quantity_unit']) > 3)) {
            $invalidProperties[] = "invalid value for 'handling_unit_quantity_unit', the character length must be smaller than or equal to 3.";
        }

        if (!is_null($this->container['handling_unit_type_of_content']) && (mb_strlen($this->container['handling_unit_type_of_content']) > 1)) {
            $invalidProperties[] = "invalid value for 'handling_unit_type_of_content', the character length must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['material']) && (mb_strlen($this->container['material']) > 40)) {
            $invalidProperties[] = "invalid value for 'material', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['material_by_customer']) && (mb_strlen($this->container['material_by_customer']) > 35)) {
            $invalidProperties[] = "invalid value for 'material_by_customer', the character length must be smaller than or equal to 35.";
        }

        if (!is_null($this->container['material_name']) && (mb_strlen($this->container['material_name']) > 40)) {
            $invalidProperties[] = "invalid value for 'material_name', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['serial_number_profile']) && (mb_strlen($this->container['serial_number_profile']) > 4)) {
            $invalidProperties[] = "invalid value for 'serial_number_profile', the character length must be smaller than or equal to 4.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets batch
     *
     * @return string|null
     */
    public function getBatch()
    {
        return $this->container['batch'];
    }

    /**
     * Sets batch
     *
     * @param string|null $batch batch
     *
     * @return self
     */
    public function setBatch($batch)
    {
        if (is_null($batch)) {
            throw new \InvalidArgumentException('non-nullable batch cannot be null');
        }
        if ((mb_strlen($batch) > 10)) {
            throw new \InvalidArgumentException('invalid length for $batch when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 10.');
        }

        $this->container['batch'] = $batch;

        return $this;
    }

    /**
     * Gets delivery_document
     *
     * @return string|null
     */
    public function getDeliveryDocument()
    {
        return $this->container['delivery_document'];
    }

    /**
     * Sets delivery_document
     *
     * @param string|null $delivery_document delivery_document
     *
     * @return self
     */
    public function setDeliveryDocument($delivery_document)
    {
        if (is_null($delivery_document)) {
            throw new \InvalidArgumentException('non-nullable delivery_document cannot be null');
        }
        if ((mb_strlen($delivery_document) > 10)) {
            throw new \InvalidArgumentException('invalid length for $delivery_document when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 10.');
        }

        $this->container['delivery_document'] = $delivery_document;

        return $this;
    }

    /**
     * Gets delivery_document_item
     *
     * @return string|null
     */
    public function getDeliveryDocumentItem()
    {
        return $this->container['delivery_document_item'];
    }

    /**
     * Sets delivery_document_item
     *
     * @param string|null $delivery_document_item delivery_document_item
     *
     * @return self
     */
    public function setDeliveryDocumentItem($delivery_document_item)
    {
        if (is_null($delivery_document_item)) {
            throw new \InvalidArgumentException('non-nullable delivery_document_item cannot be null');
        }
        if ((mb_strlen($delivery_document_item) > 6)) {
            throw new \InvalidArgumentException('invalid length for $delivery_document_item when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 6.');
        }

        $this->container['delivery_document_item'] = $delivery_document_item;

        return $this;
    }

    /**
     * Gets handling_unit_external_id
     *
     * @return string|null
     */
    public function getHandlingUnitExternalId()
    {
        return $this->container['handling_unit_external_id'];
    }

    /**
     * Sets handling_unit_external_id
     *
     * @param string|null $handling_unit_external_id handling_unit_external_id
     *
     * @return self
     */
    public function setHandlingUnitExternalId($handling_unit_external_id)
    {
        if (is_null($handling_unit_external_id)) {
            throw new \InvalidArgumentException('non-nullable handling_unit_external_id cannot be null');
        }
        if ((mb_strlen($handling_unit_external_id) > 20)) {
            throw new \InvalidArgumentException('invalid length for $handling_unit_external_id when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 20.');
        }

        $this->container['handling_unit_external_id'] = $handling_unit_external_id;

        return $this;
    }

    /**
     * Gets handling_unit_internal_id
     *
     * @return string|null
     */
    public function getHandlingUnitInternalId()
    {
        return $this->container['handling_unit_internal_id'];
    }

    /**
     * Sets handling_unit_internal_id
     *
     * @param string|null $handling_unit_internal_id handling_unit_internal_id
     *
     * @return self
     */
    public function setHandlingUnitInternalId($handling_unit_internal_id)
    {
        if (is_null($handling_unit_internal_id)) {
            throw new \InvalidArgumentException('non-nullable handling_unit_internal_id cannot be null');
        }
        if ((mb_strlen($handling_unit_internal_id) > 10)) {
            throw new \InvalidArgumentException('invalid length for $handling_unit_internal_id when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 10.');
        }

        $this->container['handling_unit_internal_id'] = $handling_unit_internal_id;

        return $this;
    }

    /**
     * Gets handling_unit_item
     *
     * @return string|null
     */
    public function getHandlingUnitItem()
    {
        return $this->container['handling_unit_item'];
    }

    /**
     * Sets handling_unit_item
     *
     * @param string|null $handling_unit_item handling_unit_item
     *
     * @return self
     */
    public function setHandlingUnitItem($handling_unit_item)
    {
        if (is_null($handling_unit_item)) {
            throw new \InvalidArgumentException('non-nullable handling_unit_item cannot be null');
        }
        if ((mb_strlen($handling_unit_item) > 6)) {
            throw new \InvalidArgumentException('invalid length for $handling_unit_item when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 6.');
        }

        $this->container['handling_unit_item'] = $handling_unit_item;

        return $this;
    }

    /**
     * Gets handling_unit_nested_internal_id
     *
     * @return string|null
     */
    public function getHandlingUnitNestedInternalId()
    {
        return $this->container['handling_unit_nested_internal_id'];
    }

    /**
     * Sets handling_unit_nested_internal_id
     *
     * @param string|null $handling_unit_nested_internal_id handling_unit_nested_internal_id
     *
     * @return self
     */
    public function setHandlingUnitNestedInternalId($handling_unit_nested_internal_id)
    {
        if (is_null($handling_unit_nested_internal_id)) {
            throw new \InvalidArgumentException('non-nullable handling_unit_nested_internal_id cannot be null');
        }
        if ((mb_strlen($handling_unit_nested_internal_id) > 10)) {
            throw new \InvalidArgumentException('invalid length for $handling_unit_nested_internal_id when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 10.');
        }

        $this->container['handling_unit_nested_internal_id'] = $handling_unit_nested_internal_id;

        return $this;
    }

    /**
     * Gets handling_unit_nr_of_aux_packg_mat
     *
     * @return int|null
     */
    public function getHandlingUnitNrOfAuxPackgMat()
    {
        return $this->container['handling_unit_nr_of_aux_packg_mat'];
    }

    /**
     * Sets handling_unit_nr_of_aux_packg_mat
     *
     * @param int|null $handling_unit_nr_of_aux_packg_mat handling_unit_nr_of_aux_packg_mat
     *
     * @return self
     */
    public function setHandlingUnitNrOfAuxPackgMat($handling_unit_nr_of_aux_packg_mat)
    {
        if (is_null($handling_unit_nr_of_aux_packg_mat)) {
            throw new \InvalidArgumentException('non-nullable handling_unit_nr_of_aux_packg_mat cannot be null');
        }
        $this->container['handling_unit_nr_of_aux_packg_mat'] = $handling_unit_nr_of_aux_packg_mat;

        return $this;
    }

    /**
     * Gets handling_unit_number_of_serialnumb
     *
     * @return int|null
     */
    public function getHandlingUnitNumberOfSerialnumb()
    {
        return $this->container['handling_unit_number_of_serialnumb'];
    }

    /**
     * Sets handling_unit_number_of_serialnumb
     *
     * @param int|null $handling_unit_number_of_serialnumb handling_unit_number_of_serialnumb
     *
     * @return self
     */
    public function setHandlingUnitNumberOfSerialnumb($handling_unit_number_of_serialnumb)
    {
        if (is_null($handling_unit_number_of_serialnumb)) {
            throw new \InvalidArgumentException('non-nullable handling_unit_number_of_serialnumb cannot be null');
        }
        $this->container['handling_unit_number_of_serialnumb'] = $handling_unit_number_of_serialnumb;

        return $this;
    }

    /**
     * Gets handling_unit_quantity
     *
     * @return float|null
     */
    public function getHandlingUnitQuantity()
    {
        return $this->container['handling_unit_quantity'];
    }

    /**
     * Sets handling_unit_quantity
     *
     * @param float|null $handling_unit_quantity handling_unit_quantity
     *
     * @return self
     */
    public function setHandlingUnitQuantity($handling_unit_quantity)
    {
        if (is_null($handling_unit_quantity)) {
            throw new \InvalidArgumentException('non-nullable handling_unit_quantity cannot be null');
        }


        $this->container['handling_unit_quantity'] = $handling_unit_quantity;

        return $this;
    }

    /**
     * Gets handling_unit_quantity_unit
     *
     * @return string|null
     */
    public function getHandlingUnitQuantityUnit()
    {
        return $this->container['handling_unit_quantity_unit'];
    }

    /**
     * Sets handling_unit_quantity_unit
     *
     * @param string|null $handling_unit_quantity_unit handling_unit_quantity_unit
     *
     * @return self
     */
    public function setHandlingUnitQuantityUnit($handling_unit_quantity_unit)
    {
        if (is_null($handling_unit_quantity_unit)) {
            throw new \InvalidArgumentException('non-nullable handling_unit_quantity_unit cannot be null');
        }
        if ((mb_strlen($handling_unit_quantity_unit) > 3)) {
            throw new \InvalidArgumentException('invalid length for $handling_unit_quantity_unit when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 3.');
        }

        $this->container['handling_unit_quantity_unit'] = $handling_unit_quantity_unit;

        return $this;
    }

    /**
     * Gets handling_unit_type_of_content
     *
     * @return string|null
     */
    public function getHandlingUnitTypeOfContent()
    {
        return $this->container['handling_unit_type_of_content'];
    }

    /**
     * Sets handling_unit_type_of_content
     *
     * @param string|null $handling_unit_type_of_content handling_unit_type_of_content
     *
     * @return self
     */
    public function setHandlingUnitTypeOfContent($handling_unit_type_of_content)
    {
        if (is_null($handling_unit_type_of_content)) {
            throw new \InvalidArgumentException('non-nullable handling_unit_type_of_content cannot be null');
        }
        if ((mb_strlen($handling_unit_type_of_content) > 1)) {
            throw new \InvalidArgumentException('invalid length for $handling_unit_type_of_content when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 1.');
        }

        $this->container['handling_unit_type_of_content'] = $handling_unit_type_of_content;

        return $this;
    }

    /**
     * Gets material
     *
     * @return string|null
     */
    public function getMaterial()
    {
        return $this->container['material'];
    }

    /**
     * Sets material
     *
     * @param string|null $material material
     *
     * @return self
     */
    public function setMaterial($material)
    {
        if (is_null($material)) {
            throw new \InvalidArgumentException('non-nullable material cannot be null');
        }
        if ((mb_strlen($material) > 40)) {
            throw new \InvalidArgumentException('invalid length for $material when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 40.');
        }

        $this->container['material'] = $material;

        return $this;
    }

    /**
     * Gets material_by_customer
     *
     * @return string|null
     */
    public function getMaterialByCustomer()
    {
        return $this->container['material_by_customer'];
    }

    /**
     * Sets material_by_customer
     *
     * @param string|null $material_by_customer material_by_customer
     *
     * @return self
     */
    public function setMaterialByCustomer($material_by_customer)
    {
        if (is_null($material_by_customer)) {
            throw new \InvalidArgumentException('non-nullable material_by_customer cannot be null');
        }
        if ((mb_strlen($material_by_customer) > 35)) {
            throw new \InvalidArgumentException('invalid length for $material_by_customer when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 35.');
        }

        $this->container['material_by_customer'] = $material_by_customer;

        return $this;
    }

    /**
     * Gets material_name
     *
     * @return string|null
     */
    public function getMaterialName()
    {
        return $this->container['material_name'];
    }

    /**
     * Sets material_name
     *
     * @param string|null $material_name material_name
     *
     * @return self
     */
    public function setMaterialName($material_name)
    {
        if (is_null($material_name)) {
            throw new \InvalidArgumentException('non-nullable material_name cannot be null');
        }
        if ((mb_strlen($material_name) > 40)) {
            throw new \InvalidArgumentException('invalid length for $material_name when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 40.');
        }

        $this->container['material_name'] = $material_name;

        return $this;
    }

    /**
     * Gets serial_number_profile
     *
     * @return string|null
     */
    public function getSerialNumberProfile()
    {
        return $this->container['serial_number_profile'];
    }

    /**
     * Sets serial_number_profile
     *
     * @param string|null $serial_number_profile serial_number_profile
     *
     * @return self
     */
    public function setSerialNumberProfile($serial_number_profile)
    {
        if (is_null($serial_number_profile)) {
            throw new \InvalidArgumentException('non-nullable serial_number_profile cannot be null');
        }
        if ((mb_strlen($serial_number_profile) > 4)) {
            throw new \InvalidArgumentException('invalid length for $serial_number_profile when calling APIOUTBOUNDDELIVERYSRVAHandlingUnitItemDeliveryType., must be smaller than or equal to 4.');
        }

        $this->container['serial_number_profile'] = $serial_number_profile;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


