<?php
/**
 * APIOUTBOUNDDELIVERYSRVAOutbDeliveryItemTextType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Outbound Delivery (A2X)
 *
 * This service enables you to create, read, update and delete outbound deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\OutboundDelivery\Model;

use \ArrayAccess;
use \BeLenka\SAP\OutboundDelivery\ObjectSerializer;

/**
 * APIOUTBOUNDDELIVERYSRVAOutbDeliveryItemTextType Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class APIOUTBOUNDDELIVERYSRVAOutbDeliveryItemTextType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'API_OUTBOUND_DELIVERY_SRV.A_OutbDeliveryItemTextType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'delivery_document' => 'string',
        'delivery_document_item' => 'string',
        'text_element' => 'string',
        'language' => 'string',
        'text_element_description' => 'string',
        'text_element_text' => 'string',
        'delivery_long_text_is_formatted' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'delivery_document' => null,
        'delivery_document_item' => null,
        'text_element' => null,
        'language' => null,
        'text_element_description' => null,
        'text_element_text' => null,
        'delivery_long_text_is_formatted' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'delivery_document' => false,
		'delivery_document_item' => false,
		'text_element' => false,
		'language' => false,
		'text_element_description' => false,
		'text_element_text' => false,
		'delivery_long_text_is_formatted' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'delivery_document' => 'DeliveryDocument',
        'delivery_document_item' => 'DeliveryDocumentItem',
        'text_element' => 'TextElement',
        'language' => 'Language',
        'text_element_description' => 'TextElementDescription',
        'text_element_text' => 'TextElementText',
        'delivery_long_text_is_formatted' => 'DeliveryLongTextIsFormatted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'delivery_document' => 'setDeliveryDocument',
        'delivery_document_item' => 'setDeliveryDocumentItem',
        'text_element' => 'setTextElement',
        'language' => 'setLanguage',
        'text_element_description' => 'setTextElementDescription',
        'text_element_text' => 'setTextElementText',
        'delivery_long_text_is_formatted' => 'setDeliveryLongTextIsFormatted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'delivery_document' => 'getDeliveryDocument',
        'delivery_document_item' => 'getDeliveryDocumentItem',
        'text_element' => 'getTextElement',
        'language' => 'getLanguage',
        'text_element_description' => 'getTextElementDescription',
        'text_element_text' => 'getTextElementText',
        'delivery_long_text_is_formatted' => 'getDeliveryLongTextIsFormatted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('delivery_document', $data ?? [], null);
        $this->setIfExists('delivery_document_item', $data ?? [], null);
        $this->setIfExists('text_element', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('text_element_description', $data ?? [], null);
        $this->setIfExists('text_element_text', $data ?? [], null);
        $this->setIfExists('delivery_long_text_is_formatted', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['delivery_document']) && (mb_strlen($this->container['delivery_document']) > 10)) {
            $invalidProperties[] = "invalid value for 'delivery_document', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['delivery_document_item']) && (mb_strlen($this->container['delivery_document_item']) > 6)) {
            $invalidProperties[] = "invalid value for 'delivery_document_item', the character length must be smaller than or equal to 6.";
        }

        if (!is_null($this->container['text_element']) && (mb_strlen($this->container['text_element']) > 4)) {
            $invalidProperties[] = "invalid value for 'text_element', the character length must be smaller than or equal to 4.";
        }

        if (!is_null($this->container['language']) && (mb_strlen($this->container['language']) > 2)) {
            $invalidProperties[] = "invalid value for 'language', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['text_element_description']) && (mb_strlen($this->container['text_element_description']) > 30)) {
            $invalidProperties[] = "invalid value for 'text_element_description', the character length must be smaller than or equal to 30.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets delivery_document
     *
     * @return string|null
     */
    public function getDeliveryDocument()
    {
        return $this->container['delivery_document'];
    }

    /**
     * Sets delivery_document
     *
     * @param string|null $delivery_document delivery_document
     *
     * @return self
     */
    public function setDeliveryDocument($delivery_document)
    {
        if (is_null($delivery_document)) {
            throw new \InvalidArgumentException('non-nullable delivery_document cannot be null');
        }
        if ((mb_strlen($delivery_document) > 10)) {
            throw new \InvalidArgumentException('invalid length for $delivery_document when calling APIOUTBOUNDDELIVERYSRVAOutbDeliveryItemTextType., must be smaller than or equal to 10.');
        }

        $this->container['delivery_document'] = $delivery_document;

        return $this;
    }

    /**
     * Gets delivery_document_item
     *
     * @return string|null
     */
    public function getDeliveryDocumentItem()
    {
        return $this->container['delivery_document_item'];
    }

    /**
     * Sets delivery_document_item
     *
     * @param string|null $delivery_document_item delivery_document_item
     *
     * @return self
     */
    public function setDeliveryDocumentItem($delivery_document_item)
    {
        if (is_null($delivery_document_item)) {
            throw new \InvalidArgumentException('non-nullable delivery_document_item cannot be null');
        }
        if ((mb_strlen($delivery_document_item) > 6)) {
            throw new \InvalidArgumentException('invalid length for $delivery_document_item when calling APIOUTBOUNDDELIVERYSRVAOutbDeliveryItemTextType., must be smaller than or equal to 6.');
        }

        $this->container['delivery_document_item'] = $delivery_document_item;

        return $this;
    }

    /**
     * Gets text_element
     *
     * @return string|null
     */
    public function getTextElement()
    {
        return $this->container['text_element'];
    }

    /**
     * Sets text_element
     *
     * @param string|null $text_element text_element
     *
     * @return self
     */
    public function setTextElement($text_element)
    {
        if (is_null($text_element)) {
            throw new \InvalidArgumentException('non-nullable text_element cannot be null');
        }
        if ((mb_strlen($text_element) > 4)) {
            throw new \InvalidArgumentException('invalid length for $text_element when calling APIOUTBOUNDDELIVERYSRVAOutbDeliveryItemTextType., must be smaller than or equal to 4.');
        }

        $this->container['text_element'] = $text_element;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        if ((mb_strlen($language) > 2)) {
            throw new \InvalidArgumentException('invalid length for $language when calling APIOUTBOUNDDELIVERYSRVAOutbDeliveryItemTextType., must be smaller than or equal to 2.');
        }

        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets text_element_description
     *
     * @return string|null
     */
    public function getTextElementDescription()
    {
        return $this->container['text_element_description'];
    }

    /**
     * Sets text_element_description
     *
     * @param string|null $text_element_description text_element_description
     *
     * @return self
     */
    public function setTextElementDescription($text_element_description)
    {
        if (is_null($text_element_description)) {
            throw new \InvalidArgumentException('non-nullable text_element_description cannot be null');
        }
        if ((mb_strlen($text_element_description) > 30)) {
            throw new \InvalidArgumentException('invalid length for $text_element_description when calling APIOUTBOUNDDELIVERYSRVAOutbDeliveryItemTextType., must be smaller than or equal to 30.');
        }

        $this->container['text_element_description'] = $text_element_description;

        return $this;
    }

    /**
     * Gets text_element_text
     *
     * @return string|null
     */
    public function getTextElementText()
    {
        return $this->container['text_element_text'];
    }

    /**
     * Sets text_element_text
     *
     * @param string|null $text_element_text text_element_text
     *
     * @return self
     */
    public function setTextElementText($text_element_text)
    {
        if (is_null($text_element_text)) {
            throw new \InvalidArgumentException('non-nullable text_element_text cannot be null');
        }
        $this->container['text_element_text'] = $text_element_text;

        return $this;
    }

    /**
     * Gets delivery_long_text_is_formatted
     *
     * @return bool|null
     */
    public function getDeliveryLongTextIsFormatted()
    {
        return $this->container['delivery_long_text_is_formatted'];
    }

    /**
     * Sets delivery_long_text_is_formatted
     *
     * @param bool|null $delivery_long_text_is_formatted delivery_long_text_is_formatted
     *
     * @return self
     */
    public function setDeliveryLongTextIsFormatted($delivery_long_text_is_formatted)
    {
        if (is_null($delivery_long_text_is_formatted)) {
            throw new \InvalidArgumentException('non-nullable delivery_long_text_is_formatted cannot be null');
        }
        $this->container['delivery_long_text_is_formatted'] = $delivery_long_text_is_formatted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


