<?php
/**
 * OutboundDeliveryMaintenanceItemObjectListsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Outbound Delivery (A2X)
 *
 * This service enables you to create, read, update and delete outbound deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\OutboundDelivery\Test\Api;

use \BeLenka\SAP\OutboundDelivery\Configuration;
use \BeLenka\SAP\OutboundDelivery\ApiException;
use \BeLenka\SAP\OutboundDelivery\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OutboundDeliveryMaintenanceItemObjectListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\OutboundDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OutboundDeliveryMaintenanceItemObjectListsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aSerialNmbrDeliveryMaintenanceItemObjectListToMaintenanceItemObjectGet
     *
     * Reads maintenance item object lists of specific outbound delivery maintenance item object list header..
     *
     */
    public function testASerialNmbrDeliveryMaintenanceItemObjectListToMaintenanceItemObjectGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
